"""按域聚合导出，便于 `from app.schemas import ArticleOut` 等统一导入。"""

from app.schemas.article import (
    ArticleCategoryCreate,
    ArticleCategoryOut,
    ArticleCategoryPageOut,
    ArticleCategoryUpdate,
    ArticleCreate,
    ArticleOut,
    ArticlePageOut,
    ArticleSummaryOut,
    ArticleSummaryPageOut,
    ArticleUpdate,
)
from app.schemas.auth import (
    CaptchaOut,
    ChangePasswordIn,
    LoginIn,
    TokenOut,
)
from app.schemas.maintenance import (
    AdminLogsCleanupIn,
    AdminLogsCleanupOut,
    CaptchaCleanupOut,
    MaintenanceCountsOut,
    UploadPruneBody,
    UploadPruneResultOut,
    VisitStatsCleanupIn,
    VisitStatsCleanupOut,
)
from app.schemas.platform import PlatformSettingsOut, PlatformSettingsUpdate, PublicHomeOut
from app.schemas.site import (
    SiteCheckOut,
    SiteCreate,
    SiteFetchIn,
    SiteFetchOut,
    SiteOut,
    SitePageOut,
    SiteUpdate,
)
from app.schemas.site_category import (
    SiteCategoryCreate,
    SiteCategoryOut,
    SiteCategoryPageOut,
    SiteCategoryUpdate,
)
from app.schemas.stats import (
    AdminLogOut,
    AdminLogPageOut,
    LogActionOption,
    StatsLogActionsOut,
    StatsSummaryOut,
    TrendPageOut,
    TrendPoint,
)

__all__ = [
    "AdminLogOut",
    "AdminLogPageOut",
    "ArticleCategoryCreate",
    "ArticleCategoryOut",
    "ArticleCategoryPageOut",
    "ArticleCategoryUpdate",
    "ArticleCreate",
    "ArticleOut",
    "ArticlePageOut",
    "ArticleSummaryOut",
    "ArticleSummaryPageOut",
    "ArticleUpdate",
    "CaptchaCleanupOut",
    "CaptchaOut",
    "ChangePasswordIn",
    "LoginIn",
    "LogActionOption",
    "AdminLogsCleanupIn",
    "AdminLogsCleanupOut",
    "VisitStatsCleanupIn",
    "VisitStatsCleanupOut",
    "MaintenanceCountsOut",
    "PlatformSettingsOut",
    "PlatformSettingsUpdate",
    "PublicHomeOut",
    "SiteCategoryCreate",
    "SiteCategoryOut",
    "SiteCategoryPageOut",
    "SiteCategoryUpdate",
    "SiteCheckOut",
    "SiteCreate",
    "SiteFetchIn",
    "SiteFetchOut",
    "SiteOut",
    "SitePageOut",
    "SiteUpdate",
    "StatsLogActionsOut",
    "StatsSummaryOut",
    "TokenOut",
    "TrendPageOut",
    "TrendPoint",
    "UploadPruneBody",
    "UploadPruneResultOut",
]
