/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminBoolCell: typeof import('./components/admin/AdminBoolCell.vue')['default']
    AppErrorPanel: typeof import('./components/AppErrorPanel.vue')['default']
    ArticleCategoryDock: typeof import('./components/article/ArticleCategoryDock.vue')['default']
    ArticleCategorySidebar: typeof import('./components/article/ArticleCategorySidebar.vue')['default']
    ArticleCategoryTabs: typeof import('./components/article/ArticleCategoryTabs.vue')['default']
    ArticleCoverPlaceholder: typeof import('./components/ArticleCoverPlaceholder.vue')['default']
    ArticleDetailBody: typeof import('./components/article/ArticleDetailBody.vue')['default']
    ArticleListRow: typeof import('./components/article/ArticleListRow.vue')['default']
    ArticleQrDialog: typeof import('./components/article/ArticleQrDialog.vue')['default']
    CategoryIconPicker: typeof import('./components/admin/CategoryIconPicker.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HomeArticlesSection: typeof import('./components/home/HomeArticlesSection.vue')['default']
    HomeFeaturedBlock: typeof import('./components/home/HomeFeaturedBlock.vue')['default']
    PlatformFooter: typeof import('./components/PlatformFooter.vue')['default']
    PlatformLogoPlaceholder: typeof import('./components/PlatformLogoPlaceholder.vue')['default']
    PublicNav: typeof import('./components/PublicNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteCard: typeof import('./components/home/SiteCard.vue')['default']
    SiteCatalog: typeof import('./components/home/SiteCatalog.vue')['default']
    SiteCategoryDock: typeof import('./components/home/SiteCategoryDock.vue')['default']
    SiteCategorySidebar: typeof import('./components/home/SiteCategorySidebar.vue')['default']
    SiteLogoPlaceholder: typeof import('./components/SiteLogoPlaceholder.vue')['default']
    StatsLogsSection: typeof import('./components/admin/stats/StatsLogsSection.vue')['default']
    StatsMaintenanceSection: typeof import('./components/admin/stats/StatsMaintenanceSection.vue')['default']
    StatsOverview: typeof import('./components/admin/stats/StatsOverview.vue')['default']
    StatsTrafficSection: typeof import('./components/admin/stats/StatsTrafficSection.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
