import type { Component } from 'vue'
import {
  Apple,
  Avatar,
  Baseball,
  Basketball,
  Bell,
  Bicycle,
  Box,
  Bowl,
  Briefcase,
  Brush,
  Burger,
  Calendar,
  Camera,
  ChatDotRound,
  ChromeFilled,
  Clock,
  Cloudy,
  CoffeeCup,
  Coin,
  Collection,
  CollectionTag,
  Comment,
  Compass,
  Connection,
  CopyDocument,
  Cpu,
  CreditCard,
  DataAnalysis,
  DataBoard,
  DataLine,
  Discount,
  Document,
  Download,
  EditPen,
  Files,
  Film,
  Flag,
  Folder,
  FolderOpened,
  Football,
  Grid,
  Guide,
  Headset,
  Help,
  Histogram,
  HomeFilled,
  House,
  InfoFilled,
  Iphone,
  Key,
  Lightning,
  Link,
  List,
  Location,
  Lock,
  MagicStick,
  Management,
  MapLocation,
  Medal,
  Memo,
  Message,
  Microphone,
  MilkTea,
  Money,
  Monitor,
  Moon,
  MoonNight,
  Notebook,
  Notification,
  Odometer,
  OfficeBuilding,
  Opportunity,
  Phone,
  Picture,
  PieChart,
  Platform,
  Postcard,
  Present,
  PriceTag,
  Promotion,
  QuestionFilled,
  Rank,
  Reading,
  ReadingLamp,
  School,
  Scissor,
  Search,
  Service,
  SetUp,
  Setting,
  Share,
  Ship,
  Shop,
  ShoppingBag,
  ShoppingCart,
  Stamp,
  Star,
  StarFilled,
  Suitcase,
  Sunny,
  Sunrise,
  Ticket,
  Timer,
  Tools,
  TrendCharts,
  Trophy,
  Upload,
  User,
  Van,
  VideoCamera,
  View,
  Wallet,
  WindPower,
  FirstAidKit,
} from '@element-plus/icons-vue'

export type CategoryIconDef = {
  key: string
  label: string
  component: Component
}

/** 分类可选图标（约 100 个），key 存入后端 icon_key 字段 */
export const CATEGORY_ICONS: CategoryIconDef[] = [
  // —— 通用 / 导航 ——
  { key: 'folder', label: '文件夹', component: Folder },
  { key: 'folder-open', label: '资源包', component: FolderOpened },
  { key: 'grid', label: '网格', component: Grid },
  { key: 'list', label: '目录清单', component: List },
  { key: 'compass', label: '导航', component: Compass },
  { key: 'collection', label: '聚合', component: Collection },
  { key: 'link', label: '链接', component: Link },
  { key: 'share', label: '分享', component: Share },
  { key: 'search', label: '搜索', component: Search },
  { key: 'flag', label: '标记', component: Flag },
  { key: 'tag', label: '标签', component: PriceTag },
  { key: 'bookmark', label: '收藏', component: CollectionTag },
  { key: 'star', label: '星标', component: Star },
  { key: 'hot', label: '热门', component: StarFilled },
  { key: 'rank', label: '排行榜', component: Rank },
  { key: 'medal', label: '精选', component: Medal },

  // —— 阅读 / 内容 ——
  { key: 'reading', label: '阅读', component: Reading },
  { key: 'notebook', label: '笔记', component: Notebook },
  { key: 'memo', label: '博客随笔', component: Memo },
  { key: 'document', label: '文档', component: Document },
  { key: 'files', label: '文件', component: Files },
  { key: 'template', label: '模板资源', component: CopyDocument },
  { key: 'view', label: '资讯浏览', component: View },
  { key: 'news', label: '新闻资讯', component: InfoFilled },
  { key: 'morning', label: '早报', component: Sunrise },
  { key: 'night-read', label: '夜读', component: MoonNight },
  { key: 'comment', label: '社区讨论', component: Comment },
  { key: 'qa', label: '问答', component: QuestionFilled },
  { key: 'help', label: '帮助文档', component: Help },
  { key: 'reading-lamp', label: '学习', component: ReadingLamp },
  { key: 'postcard', label: '游记', component: Postcard },

  // —— 技术 / 开发 ——
  { key: 'monitor', label: '显示器', component: Monitor },
  { key: 'cpu', label: '算力 / AI', component: Cpu },
  { key: 'connection', label: '网络', component: Connection },
  { key: 'platform', label: '平台', component: Platform },
  { key: 'browser', label: '浏览器', component: ChromeFilled },
  { key: 'opensource', label: '开源', component: Box },
  { key: 'devops', label: '部署运维', component: SetUp },
  { key: 'download', label: '下载资源', component: Download },
  { key: 'upload', label: '云存储', component: Upload },
  { key: 'cloud', label: '云计算', component: Cloudy },
  { key: 'setting', label: '设置', component: Setting },
  { key: 'tools', label: '工具', component: Tools },
  { key: 'magic', label: '创意', component: MagicStick },
  { key: 'lightning', label: '效率快讯', component: Lightning },
  { key: 'lock', label: '安全', component: Lock },
  { key: 'key', label: '密钥', component: Key },

  // —— 数据 / 商业 ——
  { key: 'data', label: '数据', component: DataAnalysis },
  { key: 'data-line', label: '折线', component: DataLine },
  { key: 'trend', label: '趋势', component: TrendCharts },
  { key: 'pie', label: '图表', component: PieChart },
  { key: 'histogram', label: '统计分析', component: Histogram },
  { key: 'dashboard', label: '数据看板', component: DataBoard },
  { key: 'opportunity', label: '商机', component: Opportunity },
  { key: 'management', label: '运营管理', component: Management },
  { key: 'payment', label: '支付', component: CreditCard },
  { key: 'coin', label: '数字资产', component: Coin },
  { key: 'money', label: '财经', component: Money },
  { key: 'wallet', label: '金融', component: Wallet },
  { key: 'discount', label: '优惠羊毛', component: Discount },
  { key: 'promotion', label: '营销推广', component: Promotion },
  { key: 'odometer', label: '仪表', component: Odometer },

  // —— 媒体 / 设计 ——
  { key: 'video', label: '视频', component: VideoCamera },
  { key: 'film', label: '影视', component: Film },
  { key: 'picture', label: '图片', component: Picture },
  { key: 'camera', label: '摄影', component: Camera },
  { key: 'scissor', label: '视频剪辑', component: Scissor },
  { key: 'headset', label: '音频', component: Headset },
  { key: 'podcast', label: '播客', component: Microphone },
  { key: 'edit', label: '编辑', component: EditPen },
  { key: 'brush', label: '设计', component: Brush },

  // —— 购物 / 消费 ——
  { key: 'shop', label: '购物', component: Shop },
  { key: 'cart', label: '购物车', component: ShoppingCart },
  { key: 'shopping-bag', label: '种草好物', component: ShoppingBag },
  { key: 'present', label: '礼物', component: Present },
  { key: 'ticket', label: '票务', component: Ticket },
  { key: 'stamp', label: '认证', component: Stamp },

  // —— 美食 / 生活 ——
  { key: 'bowl', label: '美食', component: Bowl },
  { key: 'burger', label: '快餐', component: Burger },
  { key: 'coffee', label: '咖啡', component: CoffeeCup },
  { key: 'milk-tea', label: '奶茶饮品', component: MilkTea },
  { key: 'apple', label: '水果', component: Apple },
  { key: 'sunny', label: '生活', component: Sunny },
  { key: 'moon', label: '夜间', component: Moon },
  { key: 'wind', label: '能源', component: WindPower },
  { key: 'calendar', label: '日历', component: Calendar },
  { key: 'clock', label: '时钟', component: Clock },
  { key: 'timer', label: '计时', component: Timer },

  // —— 出行 / 地理 ——
  { key: 'location', label: '位置', component: Location },
  { key: 'map', label: '地图', component: MapLocation },
  { key: 'suitcase', label: '旅行', component: Suitcase },
  { key: 'van', label: '出行', component: Van },
  { key: 'ship', label: '航运', component: Ship },
  { key: 'bicycle', label: '骑行', component: Bicycle },

  // —— 教育 / 职场 ——
  { key: 'school', label: '教育', component: School },
  { key: 'guide', label: '指南', component: Guide },
  { key: 'office', label: '企业办公', component: OfficeBuilding },
  { key: 'briefcase', label: '职场商务', component: Briefcase },

  // —— 运动 / 健康 ——
  { key: 'trophy', label: '竞技', component: Trophy },
  { key: 'basketball', label: '篮球', component: Basketball },
  { key: 'football', label: '足球', component: Football },
  { key: 'baseball', label: '棒球', component: Baseball },
  { key: 'health', label: '健康医疗', component: FirstAidKit },

  // —— 社交 / 通讯 ——
  { key: 'chat', label: '对话', component: ChatDotRound },
  { key: 'message', label: '消息', component: Message },
  { key: 'notification', label: '订阅资讯', component: Notification },
  { key: 'bell', label: '通知', component: Bell },
  { key: 'phone', label: '手机', component: Phone },
  { key: 'mobile', label: '移动应用', component: Iphone },
  { key: 'social', label: '社交', component: Avatar },
  { key: 'service', label: '服务', component: Service },
  { key: 'user', label: '用户', component: User },
  { key: 'home', label: '首页', component: House },
  { key: 'home-filled', label: '主页', component: HomeFilled },
]

const iconMap: Record<string, Component> = Object.fromEntries(
  CATEGORY_ICONS.map(({ key, component }) => [key, component]),
)

export function categoryIconComponent(key: string | null | undefined): Component | null {
  if (!key) return null
  return iconMap[key] ?? null
}

export function categoryIconLabel(key: string | null | undefined): string {
  if (!key) return '无'
  return CATEGORY_ICONS.find((item) => item.key === key)?.label ?? key
}
